### PR TITLE
use regex to match multi-words university names

### PR DESCRIPTION
**Pull request by e-naharnovic**
This change allows to make multi-word requests (not the whole university name and not partial match of one word like requesting "aban" and getting "saban")
Examples: `Middle East`, `Civil Aviation`. We get relevant **non-empty** result.
Checked with only `name` parameter and with both `name` and `country` parameters

### CODE REVIEW

**Comment by e-naharnovic** [comment]
@yigitguler could you please review and give feedback?

**Comment by yigitguler** [comment]
@e-naharnovic, Thanks for the PR.

The PR looks OK, but I am not sure if we should remove the existing "startswith" logic. I think to make a "search" in the university name and "getting typeahead suggestions" are different use cases and they have to be treated differently. 

I propose to implement your update under a different request parameter. Something like "?name_contains=Aviation"

How does it sound?

**Comment by e-naharnovic** [comment]
@yigitguler Thanks for the feedback and the idea. That sounds nice. I also thought about removing previous logic. Smb can use it in a current working app. I will make another request soon with a new request parameter.

**Comment by yigitguler** [comment]
Thank you

**Comment by e-naharnovic** [comment]
PR with a new request parameter https://github.com/Hipo/university-domains-list-api/pull/14

**Pull request closed without merging**
