### PR TITLE
Updated the api to newer versions of tools

### PR DESCRIPTION
**Pull request by aviiciii**
- Flask updated from 1.0.0 to 2.3.2
- PyTrie from 0.2.0 to 0.4.0
- Used jsonify to dump response 
- Added detailed requirements.txt

### CODE REVIEW

**Comment by yigitguler** [comment]
Hi, this is a great improvement. Thank you.
 - Does this create any change in the response?
 - Also is there a reason you pinned all sub-requirements as well?

**Comment by aviiciii** [comment]
No, there is no change in the response but the method the response is encapsulated is done using `jsonify`.
I just pinned the sub-requirements as it would be easier to be on the same page while editing the api in the future.

**Comment by yigitguler** [comment]
Thanks!

**Comment by aviiciii** [comment]
Cool! @yigitguler I like to work more on this repo, by adding different fileds to the api filtering, shall i go ahead?

**Comment by yigitguler** [comment]
Yes, thanks for the contribution.

**Pull request merged**
